<?php
/********************************************************************************
 * @Project    KYG Framework for business
 * @Version    1.0.0
 *
 * @Copyright  (C) 2025 Kataev Yaroslav Georgievich 
 * @E-mail     yaroslaw74@gmail.com
 * @License    GNU General Public License version 3 or later; see LICENSE.md
 ********************************************************************************/
namespace App\Modules\Administrations\Resource;

use Symfony\Component\Translation\Translator;

class ArrayAccess
{
    private $Themes = [
        'base' => ['key' => 'themes.base'],
        'black-tie' => ['key' => 'themes.black-tie'],
        'blitzer' => ['key' => 'themes.blitzer'],
        'cupertino' => ['key' => 'themes.cupertino'],
        'dark-hive' => ['key' => 'themes.dark-hive'],
        'dot-luv' => ['key' => 'themes.dot-luv'],
        'eggplant' => ['key' => 'themes.eggplant'],
        'excite-bike' => ['key' => 'themes.excite-bike'],
        'flick' => ['key' => 'themes.flick'],
        'hot-sneaks' => ['key' => 'themes.hot-sneaks'],
        'humanity' => ['key' => 'themes.humanity'],
        'le-frog' => ['key' => 'themes.le-frog'],
        'mint-choc' => ['key' => 'themes.mint-choc'],
        'overcast' => ['key' => 'themes.overcast'],
        'pepper-grinder' => ['key' => 'themes.pepper-grinder'],
        'redmond' => ['key' => 'themes.redmond'],
        'smoothness' => ['key' => 'themes.smoothness'],
        'south-street' => ['key' => 'themes.south-street'],
        'start' => ['key' => 'themes.start'],
        'sunny' => ['key' => 'themes.sunny'],
        'swanky-purse' => ['key' => 'themes.swanky-purse'],
        'trontastic' => ['key' => 'themes.trontastic'],
        'ui-darkness' => ['key' => 'themes.ui-darkness'],
        'ui-lightness' => ['key' => 'themes.ui-lightness'],
        'vader' => ['key' => 'themes.vader']
    ];
    public $Effects = [
        'blind' => ['key' => 'effects.blind'],
        'bounce' => ['key' => 'effects.bounce'],
        'clip' => ['key' => 'effects.clip'],
        'drop' => ['key' => 'effects.drop'],
        'fold' => ['key' => 'effects.fold'],
        'highlight' => ['key' => 'effects.highlight'],
        'puff' => ['key' => 'effects.puff'],
        'pulsate' => ['key' => 'effects.pulsate'],
        'scale' => ['key' => 'effects.scale'],
        'shake' => ['key' => 'effects.shake'],
        'size' => ['key' => 'effects.size'],
        'slide' => ['key' => 'effects.slide'],
        'transfer' => ['key' => 'effects.transfer']
    ];
    public $TimeZone = [];
    public $DataFormat = [
        'YYYY.MM.DD' => ['format' => 'Y.m.d'],
        'YYYY-MM-DD' => ['format' => 'Y-m-d'],
        'YYYY/MM/DD' => ['format' => 'Y/m/d'],
        'yyyy.mm.dd' => ['format' => 'Y.n.j'],
        'yyyy-mm-dd' => ['format' => 'Y-n-j'],
        'yyyy/mm/dd' => ['format' => 'Y/n/j'],
        'YYYY.DD.MM' => ['format' => 'Y.d.m'],
        'YYYY-DD-MM' => ['format' => 'Y-d-m'],
        'YYYY/DD/MM' => ['format' => 'Y/d/m'],
        'yyyy.dd.mm' => ['format' => 'Y.j.n'],
        'yyyy-dd-mm' => ['format' => 'Y-j-n'],
        'YYYY/dd/mm' => ['format' => 'Y/j/n'],
        'dd.mm.yyyy' => ['format' => 'j.n.Y'],
        'dd-mm-yyyy' => ['format' => 'j-n-Y'],
        'dd/mm/yyyy' => ['format' => 'j/n/Y'],
        'DD.MM.YYYY' => ['format' => 'd.m.Y'],
        'DD-MM-YYYY' => ['format' => 'd-m-Y'],
        'DD/MM/YYYY' => ['format' => 'd/m/Y'],
        'mm.dd.yyyy' => ['format' => 'n.j.Y'],
        'mm-dd-yyyy' => ['format' => 'n-j-Y'],
        'mm/dd/yyyy' => ['format' => 'n/j/Y'],
        'MM.DD.YYYY' => ['format' => 'm.d.Y'],
        'MM-DD-YYYY' => ['format' => 'm-d-Y'],
        'MM/DD/YYYY' => ['format' => 'm/d/Y']
    ];
    public $TimeFormat = [
        'HH:MM:SS' => ['format' => 'H:i:s'],
        'HH.MM.SS' => ['format' => 'H.i.s'],
        'HH,MM,SS' => ['format' => 'H,i,s'],
        'HH:MM:SS am/pm' => ['format' => 'h:i:s a'],
        'HH.MM.SS am/pm' => ['format' => 'h.i.s a'],
        'HH,MM,SS am/pm' => ['format' => 'h,i,s a'],
        'HH:MM:SS AM/PM' => ['format' => 'h:i:s A'],
        'HH.MM.SS AM/PM' => ['format' => 'h.i.s A'],
        'HH,MM,SS AM/PM' => ['format' => 'h,i,s A'],
        'hh:mm:ss' => ['format' => 'G:i:s'],
        'hh.mm.ss' => ['format' => 'G.i.s'],
        'hh,mm,ss' => ['format' => 'G,i,s'],
        'hh:mm:ss am/pm' => ['format' => 'g:i:s a'],
        'hh.mm.ss am/pm' => ['format' => 'g.i.s a'],
        'hh,mm,ss am/pm' => ['format' => 'g,i,s a'],
        'hh:mm:ss AM/PM' => ['format' => 'g:i:s A'],
        'hh.mm.ss AM/PM' => ['format' => 'g.i.s A'],
        'hh,mm,ss AM/PM' => ['format' => 'g,i,s A']
    ];
    public $LanguageCKEditor = ['af', 'ar', 'ast', 'az', 'bg', 'bn', 'bs', 'ca', 'cs', 'da', 'de', 'de-ch', 'el', 'en-au', 'en-gb', 'eo', 'es', 'es-co', 'et', 'eu', 'fa', 'fi', 'fr', 'gl', 'gu', 'he', 'hi', 'hr', 'hu', 'hy', 'id', 'it', 'ja', 'jv', 'kk', 'km', 'kn', 'ko', 'ku', 'lt', 'lv', 'ms', 'nb', 'ne', 'nl', 'no', 'oc', 'pl', 'pt', 'pt-br', 'ro', 'ru', 'si', 'sk', 'sl', 'sq', 'sr', 'sr-latn', 'sv', 'th', 'tk', 'tr', 'tt', 'ug', 'uk', 'ur', 'uz', 'vi', 'zh', 'zh-cn'];
    public $LanguageData = ['af', 'ar', 'ar-DZ', 'az', 'be', 'bg', 'bs', 'ca', 'cs', 'cy-GB', 'da', 'de', 'de-AT', 'el', 'en-AU', 'en-GB', 'en-NZ', 'eo', 'es', 'et', 'eu', 'fa', 'fi', 'fo', 'fr', 'fr-CA', 'fr-CH', 'gl', 'he', 'hi', 'hr', 'hu', 'hy', 'id', 'is', 'it', 'it-CH', 'ja', 'ka', 'kk', 'km', 'ko', 'ky', 'lb', 'lt', 'lv', 'mk', 'ml', 'ms', 'nb', 'nl', 'nl-BE', 'nn', 'no', 'pl', 'pt', 'pt-BR', 'rm', 'ro', 'ru', 'sk', 'sl', 'sq', 'sr', 'sr-SR', 'sv', 'ta', 'ta', 'tj', 'tr', 'uk', 'vi', 'zh-CN', 'zh-HK', 'zh-TW'];
    public $LanguageList = [
        'af-NA' => ['name' => 'Afrikaans (Namibië)', 'rtl' => false],
        'af-ZA' => ['name' => 'Afrikaans (Suid-Afrika)', 'rtl' => false],
        'agq-CM' => ['nmae' => 'Aghem (Kàmàlûŋ)', 'rtl' => false],
        'ak-GH' => ['name' => 'Akan (Gaana)', 'rtl' => false],
        'am-ET' => ['name' => 'አማርኛ (ኢትዮጵያ)', 'rtl' => false],
        'ar-AE' => ['name' => 'العربية (الإمارات العربية المتحدة)', 'rtl' => true],
        'ar-BH' => ['name' => 'العربية (البحرين)', 'rtl' => true],
        'ar-DJ' => ['name' => 'العربية (جيبوتي)', 'rtl' => true],
        'ar-DZ' => ['name' => 'العربية (الجزائر)', 'rtl' => true],
        'ar-EG' => ['name' => 'العربية (مصر)', 'rtl' => true],
        'ar-EH' => ['name' => 'العربية (الصحراء الغربية)', 'rtl' => true],
        'ar-ER' => ['name' => 'العربية (إريتريا)', 'rtl' => true],
        'ar-IL' => ['name' => 'العربية (إسرائيل)', 'rtl' => true],
        'ar-IQ' => ['name' => 'العربية (العراق)', 'rtl' => true],
        'ar-JO' => ['name' => 'العربية (الأردن)', 'rtl' => true],
        'ar-KM' => ['name' => 'العربية (جزر القمر)', 'rtl' => true],
        'ar-KW' => ['name' => 'العربية (الكويت)', 'rtl' => true],
        'ar-LB' => ['name' => 'العربية (لبنان)', 'rtl' => true],
        'ar-LY' => ['nmae' => 'العربية (ليبيا)', 'rtl' => true],
        'ar-MA' => ['nmae' => 'العربية (المغرب)', 'rtl' => true],
        'ar-MR' => ['name' => 'العربية (موريتانيا)', 'rtl' => true],
        'ar-OM' => ['nmae' => 'العربية (عُمان)', 'rtl' => true],
        'ar-PS' => ['name' => 'العربية (الأراضي الفلسطينية)', 'rtl' => true],
        'ar-QA' => ['name' => 'العربية (قطر)', 'rtl' => true],
        'ar-SA' => ['name' => 'العربية (المملكة العربية السعودية)', 'rtl' => true],
        'ar-SD' => ['name' => 'العربية (السودان)', 'rtl' => true],
        'ar-SO' => ['name' => 'العربية (الصومال)', 'rtl' => true],
        'ar-SS' => ['name' => 'العربية (جنوب السودان)', 'rtl' => true],
        'ar-SY' => ['name' => 'العربية (سوريا)', 'rtl' => true],
        'ar-TD' => ['name' => 'العربية (تشاد)', 'rtl' => true],
        'ar-TN' => ['name' => 'العربية (تونس)', 'rtl' => true],
        'ar-YE' => ['name' => 'العربية (اليمن)', 'rtl' => true],
        'as-IN' => ['nmae' => 'অসমীয়া (ভারত)', 'rtl' => false],
        'asa-TZ' => ['name' => 'Kipare (Tadhania)', 'rtl' => false],
        'ast-ES' => ['name' => 'asturianu (España)', 'rtl' => false],
        'az-Cyrl-AZ' => ['name' => 'азәрбајҹан (Азәрбајҹан)', 'rtl' => false],
        'az-Latn-AZ' => ['name' => 'azərbaycan (Azərbaycan)', 'rtl' => false],
        'bas-CM' => ['name' => 'Ɓàsàa (Kàmɛ̀rûn)', 'rtl' => false],
        'be-BY' => ['name' => 'беларуская (Беларусь)', 'rtl' => false],
        'bem-ZM' => ['name' => 'Ichibemba (Zambia)', 'rtl' => false],
        'bez-TZ' => ['name' => 'Hibena (Hutanzania)', 'rtl' => false],
        'bg-BG' => ['name' => 'български (България)', 'rtl' => false],
        'bm-ML' => ['name' => 'bamanakan (Mali)', 'rtl' => false],
        'bn-BD' => ['name' => 'বাংলা (বাংলাদেশ)', 'rtl' => false],
        'bn-IN' => ['name' => 'বাংলা (ভারত)', 'rtl' => false],
        'bo-CN' => ['name' => 'བོད་སྐད་ (རྒྱ་ནག)', 'rtl' => false],
        'bo-IN' => ['name' => 'བོད་སྐད་ (རྒྱ་གར་)', 'rtl' => false],
        'br-FR' => ['name' => 'brezhoneg (Frañs)', 'rtl' => false],
        'brx-IN' => ['name' => 'बड़ो (भारत)', 'rtl' => false],
        'bs-Cyrl-BA' => ['name' => 'босански (Босна и Херцеговина)', 'rtl' => false],
        'bs-Latn-BA' => ['name' => 'bosanski (latinica, Bosna i Hercegovina)', 'rtl' => false],
        'ca-AD' => ['name' => 'català (Andorra)', 'rtl' => false],
        'ca-ES' => ['name' => 'català (Espanya)', 'rtl' => false],
        'ca-FR' => ['name' => 'català (França)', 'rtl' => false],
        'ca-IT' => ['name' => 'català (Itàlia)', 'rtl' => false],
        'ccp-BD' => ['name' => '𑄌𑄋𑄴𑄟𑄳𑄦 (𑄝𑄁𑄣𑄘𑄬𑄌𑄴)', 'rtl' => false],
        'ccp-IN' => ['name' => '𑄌𑄋𑄴𑄟𑄳𑄦 (𑄞𑄢𑄧𑄖𑄴)', 'rtl' => false],
        'ce-RU' => ['name' => 'нохчийн (Росси)', 'rtl' => false],
        'cgg-UG' => ['name' => 'Rukiga (Uganda)', 'rtl' => false],
        'chr-US' => ['name' => 'ᏣᎳᎩ (ᏌᏊ ᎢᏳᎾᎵᏍᏔᏅ ᏍᎦᏚᎩ)', 'rtl' => false],
        'ckb-IQ' => ['name' => 'کوردیی ناوەندی (عێراق)', 'rtl' => true],
        'ckb-IR' => ['name' => 'کوردیی ناوەندی (ئێران)', 'rtl' => true],
        'cs-CZ' => ['name' => 'čeština (Česko)', 'rtl' => false],
        'cy-GB' => ['name' => 'Cymraeg (Y Deyrnas Unedig)', 'rtl' => false],
        'da-DK' => ['name' => 'dansk (Danmark)', 'rtl' => false],
        'da-GL' => ['name' => 'dansk (Grønland)', 'rtl' => false],
        'dav-KE' => ['name' => 'Kitaita (Kenya)', 'rtl' => false],
        'de-AT' => ['name' => 'Deutsch (Österreich)', 'rtl' => false],
        'de-BE' => ['name' => 'Deutsch (Belgien)', 'rtl' => false],
        'de-CH' => ['name' => 'Deutsch (Schweiz)', 'rtl' => false],
        'de-DE' => ['name' => 'Deutsch (Deutschland)', 'rtl' => false],
        'de-IT' => ['name' => 'Deutsch (Italien)', 'rtl' => false],
        'de-LI' => ['name' => 'Deutsch (Liechtenstein)', 'rtl' => false],
        'de-LU' => ['name' => 'Deutsch (Luxemburg)', 'rtl' => false],
        'dje-NE' => ['name' => 'Zarmaciine (Nižer)', 'rtl' => false],
        'dsb-DE' => ['name' => 'dolnoserbšćina (Nimska)', 'rtl' => false],
        'dua-CM' => ['name' => 'duálá (Cameroun)', 'rtl' => false],
        'dyo-SN' => ['name' => 'joola (Senegal)', 'rtl' => false],
        'dz-BT' => ['name' => 'རྫོང་ཁ། (འབྲུག།)', 'rtl' => false],
        'ebu-KE' => ['name' => 'Kĩembu (Kenya)', 'rtl' => false],
        'ee-GH' => ['name' => 'Eʋegbe (Ghana nutome)', 'rtl' => false],
        'ee-TG' => ['name' => 'Eʋegbe (Togo nutome)', 'rtl' => false],
        'el-CY' => ['name' => 'Ελληνικά (Κύπρος)', 'rtl' => false],
        'el-GR' => ['name' => 'Ελληνικά (Ελλάδα)', 'rtl' => false],
        'en-AG' => ['name' => 'English (Antigua & Barbuda)', 'rtl' => false],
        'en-AI' => ['name' => 'English (Anguilla)', 'rtl' => false],
        'en-AS' => ['name' => 'English (American Samoa)', 'rtl' => false],
        'en-AT' => ['name' => 'English (Austria)', 'rtl' => false],
        'en-AU' => ['name' => 'English (Australia)', 'rtl' => false],
        'en-BB' => ['name' => 'English (Barbados)', 'rtl' => false],
        'en-BE' => ['name' => 'English (Belgium)', 'rtl' => false],
        'en-BI' => ['name' => 'English (Burundi)', 'rtl' => false],
        'en-BM' => ['name' => 'English (Bermuda)', 'rtl' => false],
        'en-BS' => ['name' => 'English (Bahamas)', 'rtl' => false],
        'en-BW' => ['name' => 'English (Botswana)', 'rtl' => false],
        'en-BZ' => ['name' => 'English (Belize)', 'rtl' => false],
        'en-CA' => ['name' => 'English (Canada)', 'rtl' => false],
        'en-CC' => ['name' => 'English (Cocos [Keeling] Islands)', 'rtl' => false],
        'en-CH' => ['name' => 'English (Switzerland)', 'rtl' => false],
        'en-CK' => ['name' => 'English (Cook Islands)', 'rtl' => false],
        'en-CM' => ['name' => 'English (Cameroon)', 'rtl' => false],
        'en-CX' => ['name' => 'English (Christmas Island)', 'rtl' => false],
        'en-CY' => ['name' => 'English (Cyprus)', 'rtl' => false],
        'en-DE' => ['name' => 'English (Germany)', 'rtl' => false],
        'en-DG' => ['name' => 'English (Diego Garcia)', 'rtl' => false],
        'en-DK' => ['name' => 'English (Denmark)', 'rtl' => false],
        'en-DM' => ['name' => 'English (Dominica)', 'rtl' => false],
        'en-ER' => ['name' => 'English (Eritrea)', 'rtl' => false],
        'en-FI' => ['name' => 'English (Finland)', 'rtl' => false],
        'en-FJ' => ['name' => 'English (Fiji)', 'rtl' => false],
        'en-FK' => ['name' => 'English (Falkland Islands)', 'rtl' => false],
        'en-FM' => ['name' => 'English (Micronesia)', 'rtl' => false],
        'en-GB' => ['name' => 'English (United Kingdom)', 'rtl' => false],
        'en-GD' => ['name' => 'English (Grenada)', 'rtl' => false],
        'en-GG' => ['name' => 'English (Guernsey)', 'rtl' => false],
        'en-GH' => ['name' => 'English (Ghana)', 'rtl' => false],
        'en-GI' => ['name' => 'English (Gibraltar)', 'rtl' => false],
        'en-GM' => ['name' => 'English (Gambia)', 'rtl' => false],
        'en-GU' => ['name' => 'English (Guam)', 'rtl' => false],
        'en-GY' => ['name' => 'English (Guyana)', 'rtl' => false],
        'en-HK' => ['name' => 'English (Hong Kong SAR China)', 'rtl' => false],
        'en-IE' => ['name' => 'English (Ireland)', 'rtl' => false],
        'en-IL' => ['name' => 'English (Israel)', 'rtl' => false],
        'en-IM' => ['name' => 'English (Isle of Man)', 'rtl' => false],
        'en-IN' => ['name' => 'English (India)', 'rtl' => false],
        'en-IO' => ['name' => 'English (British Indian Ocean Territory)', 'rtl' => false],
        'en-JE' => ['name' => 'English (Jersey)', 'rtl' => false],
        'en-JM' => ['name' => 'English (Jamaica)', 'rtl' => false],
        'en-KE' => ['name' => 'English (Kenya)', 'rtl' => false],
        'en-KI' => ['name' => 'English (Kiribati)', 'rtl' => false],
        'en-KN' => ['name' => 'English (St. Kitts & Nevis)', 'rtl' => false],
        'en-KY' => ['name' => 'English (Cayman Islands)', 'rtl' => false],
        'en-LC' => ['name' => 'English (St. Lucia)', 'rtl' => false],
        'en-LR' => ['name' => 'English (Liberia)', 'rtl' => false],
        'en-LS' => ['name' => 'English (Lesotho)', 'rtl' => false],
        'en-MG' => ['name' => 'English (Madagascar)', 'rtl' => false],
        'en-MH' => ['name' => 'English (Marshall Islands)', 'rtl' => false],
        'en-MO' => ['name' => 'English (Macau SAR China)', 'rtl' => false],
        'en-MP' => ['name' => 'English (Northern Mariana Islands)', 'rtl' => false],
        'en-MS' => ['name' => 'English (Montserrat)', 'rtl' => false],
        'en-MT' => ['name' => 'English (Malta)', 'rtl' => false],
        'en-MU' => ['name' => 'English (Mauritius)', 'rtl' => false],
        'en-MW' => ['name' => 'English (Malawi)', 'rtl' => false],
        'en-MY' => ['name' => 'English (Malaysia)', 'rtl' => false],
        'en-NA' => ['name' => 'English (Namibia)', 'rtl' => false],
        'en-NF' => ['name' => 'English (Norfolk Island)', 'rtl' => false],
        'en-NG' => ['name' => 'English (Nigeria)', 'rtl' => false],
        'en-NL' => ['name' => 'English (Netherlands)', 'rtl' => false],
        'en-NR' => ['name' => 'English (Nauru)', 'rtl' => false],
        'en-NU' => ['name' => 'English (Niue)', 'rtl' => false],
        'en-NZ' => ['name' => 'English (New Zealand)', 'rtl' => false],
        'en-PG' => ['name' => 'English (Papua New Guinea)', 'rtl' => false],
        'en-PH' => ['name' => 'English (Philippines)', 'rtl' => false],
        'en-PK' => ['name' => 'English (Pakistan)', 'rtl' => false],
        'en-PN' => ['name' => 'English (Pitcairn Islands)', 'rtl' => false],
        'en-PR' => ['name' => 'English (Puerto Rico)', 'rtl' => false],
        'en-PW' => ['name' => 'English (Palau)', 'rtl' => false],
        'en-RW' => ['name' => 'English (Rwanda)', 'rtl' => false],
        'en-SB' => ['name' => 'English (Solomon Islands)', 'rtl' => false],
        'en-SC' => ['name' => 'English (Seychelles)', 'rtl' => false],
        'en-SD' => ['name' => 'English (Sudan)', 'rtl' => false],
        'en-SE' => ['name' => 'English (Sweden)', 'rtl' => false],
        'en-SG' => ['name' => 'English (Singapore)', 'rtl' => false],
        'en-SH' => ['name' => 'English (St. Helena)', 'rtl' => false],
        'en-SI' => ['name' => 'English (Slovenia)', 'rtl' => false],
        'en-SL' => ['name' => 'English (Sierra Leone)', 'rtl' => false],
        'en-SS' => ['name' => 'English (South Sudan)', 'rtl' => false],
        'en-SX' => ['name' => 'English (Sint Maarten)', 'rtl' => false],
        'en-SZ' => ['name' => 'English (Swaziland)', 'rtl' => false],
        'en-TC' => ['name' => 'English (Turks & Caicos Islands)', 'rtl' => false],
        'en-TK' => ['name' => 'English (Tokelau)', 'rtl' => false],
        'en-TO' => ['name' => 'English (Tonga)', 'rtl' => false],
        'en-TT' => ['name' => 'English (Trinidad & Tobago)', 'rtl' => false],
        'en-TV' => ['name' => 'English (Tuvalu)', 'rtl' => false],
        'en-TZ' => ['name' => 'English (Tanzania)', 'rtl' => false],
        'en-UG' => ['name' => 'English (Uganda)', 'rtl' => false],
        'en-UM' => ['name' => 'English (U.S. Outlying Islands)', 'rtl' => false],
        'en-US' => ['name' => 'English (United States)', 'rtl' => false],
        'en-VC' => ['name' => 'English (St. Vincent & Grenadines)', 'rtl' => false],
        'en-VG' => ['name' => 'English (British Virgin Islands)', 'rtl' => false],
        'en-VI' => ['name' => 'English (U.S. Virgin Islands)', 'rtl' => false],
        'en-VU' => ['name' => 'English (Vanuatu)', 'rtl' => false],
        'en-WS' => ['name' => 'English (Samoa)', 'rtl' => false],
        'en-ZA' => ['name' => 'English (South Africa)', 'rtl' => false],
        'en-ZM' => ['name' => 'English (Zambia)', 'rtl' => false],
        'en-ZW' => ['name' => 'English (Zimbabwe)', 'rtl' => false],
        'es-AR' => ['name' => 'español (Argentina)', 'rtl' => false],
        'es-BO' => ['name' => 'español (Bolivia)', 'rtl' => false],
        'es-BR' => ['name' => 'español (Brasil)', 'rtl' => false],
        'es-BZ' => ['name' => 'español (Belice)', 'rtl' => false],
        'es-CL' => ['name' => 'español (Chile)', 'rtl' => false],
        'es-CO' => ['name' => 'español (Colombia)', 'rtl' => false],
        'es-CR' => ['name' => 'español (Costa Rica)', 'rtl' => false],
        'es-CU' => ['name' => 'español (Cuba)', 'rtl' => false],
        'es-DO' => ['name' => 'español (República Dominicana)', 'rtl' => false],
        'es-EA' => ['name' => 'español (Ceuta y Melilla)', 'rtl' => false],
        'es-EC' => ['name' => 'español (Ecuador)', 'rtl' => false],
        'es-ES' => ['name' => 'español (España)', 'rtl' => false],
        'es-GQ' => ['name' => 'español (Guinea Ecuatorial)', 'rtl' => false],
        'es-GT' => ['name' => 'español (Guatemala)', 'rtl' => false],
        'es-HN' => ['name' => 'español (Honduras)', 'rtl' => false],
        'es-IC' => ['name' => 'español (Canarias)', 'rtl' => false],
        'es-MX' => ['name' => 'español (México)', 'rtl' => false],
        'es-NI' => ['name' => 'español (Nicaragua)', 'rtl' => false],
        'es-PA' => ['name' => 'español (Panamá)', 'rtl' => false],
        'es-PE' => ['name' => 'español (Perú)', 'rtl' => false],
        'es-PH' => ['name' => 'español (Filipinas)', 'rtl' => false],
        'es-PR' => ['name' => 'español (Puerto Rico)', 'rtl' => false],
        'es-PY' => ['name' => 'español (Paraguay)', 'rtl' => false],
        'es-SV' => ['name' => 'español (El Salvador)', 'rtl' => false],
        'es-US' => ['name' => 'español (Estados Unidos)', 'rtl' => false],
        'es-UY' => ['name' => 'español (Uruguay)', 'rtl' => false],
        'es-VE' => ['name' => 'español (Venezuela)', 'rtl' => false],
        'et-EE' => ['name' => 'eesti (Eesti)', 'rtl' => false],
        'eu-ES' => ['name' => 'euskara (Espainia)', 'rtl' => false],
        'ewo-CM' => ['name' => 'ewondo (Kamərún)', 'rtl' => false],
        'fa-AF' => ['name' => 'فارسی (افغانستان)', 'rtl' => true],
        'fa-IR' => ['name' => 'فارسی (ایران)', 'rtl' => true],
        'ff-CM' => ['name' => 'Pulaar (Kameruun)', 'rtl' => false],
        'ff-GN' => ['name' => 'Pulaar (Gine)', 'rtl' => false],
        'ff-MR' => ['name' => 'Pulaar (Muritani)', 'rtl' => false],
        'ff-SN' => ['name' => 'Pulaar (Senegaal)', 'rtl' => false],
        'fi-FI' => ['name' => 'suomi (Suomi)', 'rtl' => false],
        'fil-PH' => ['name' => 'Filipino (Pilipinas)', 'rtl' => false],
        'fo-DK' => ['name' => 'føroyskt (Danmark)', 'rtl' => false],
        'fo-FO' => ['name' => 'føroyskt (Føroyar)', 'rtl' => false],
        'fr-BE' => ['name' => 'français (Belgique)', 'rtl' => false],
        'fr-BF' => ['name' => 'français (Burkina Faso)', 'rtl' => false],
        'fr-BI' => ['name' => 'français (Burundi)', 'rtl' => false],
        'fr-BJ' => ['name' => 'français (Bénin)', 'rtl' => false],
        'fr-BL' => ['name' => 'français (Saint-Barthélemy)', 'rtl' => false],
        'fr-CA' => ['name' => 'français (Canada)', 'rtl' => false],
        'fr-CD' => ['name' => 'français (Congo-Kinshasa)', 'rtl' => false],
        'fr-CF' => ['name' => 'français (République centrafricaine)', 'rtl' => false],
        'fr-CG' => ['name' => 'français (Congo-Brazzaville)', 'rtl' => false],
        'fr-CH' => ['name' => 'français (Suisse)', 'rtl' => false],
        'fr-CI' => ['name' => 'français (Côte d’Ivoire)	', 'rtl' => false],
        'fr-CM' => ['name' => 'français (Cameroun)', 'rtl' => false],
        'fr-DJ' => ['name' => 'français (Djibouti)', 'rtl' => false],
        'fr-DZ' => ['name' => 'français (Algérie)', 'rtl' => false],
        'fr-FR' => ['name' => 'français (France)', 'rtl' => false],
        'fr-GA' => ['name' => 'français (Gabon)', 'rtl' => false],
        'fr-GF' => ['name' => 'français (Guyane française)', 'rtl' => false],
        'fr-GN' => ['name' => 'français (Guinée)', 'rtl' => false],
        'fr-GP' => ['name' => 'français (Guadeloupe)', 'rtl' => false],
        'fr-GQ' => ['name' => 'français (Guinée équatoriale)', 'rtl' => false],
        'fr-HT' => ['name' => 'français (Haïti)', 'rtl' => false],
        'fr-KM' => ['name' => 'français (Comores)', 'rtl' => false],
        'fr-LU' => ['name' => 'français (Luxembourg)', 'rtl' => false],
        'fr-MA' => ['name' => 'français (Maroc)', 'rtl' => false],
        'fr-MC' => ['name' => 'français (Monaco)', 'rtl' => false],
        'fr-MF' => ['name' => 'français (Saint-Martin)', 'rtl' => false],
        'fr-MG' => ['name' => 'français (Madagascar)', 'rtl' => false],
        'fr-ML' => ['name' => 'français (Mali)', 'rtl' => false],
        'fr-MQ' => ['name' => 'français (Martinique)', 'rtl' => false],
        'fr-MR' => ['name' => 'français (Mauritanie)', 'rtl' => false],
        'fr-MU' => ['name' => 'français (Maurice)', 'rtl' => false],
        'fr-NC' => ['name' => 'français (Nouvelle-Calédonie)', 'rtl' => false],
        'fr-NE' => ['name' => 'français (Niger)', 'rtl' => false],
        'fr-PF' => ['name' => 'français (Polynésie française)', 'rtl' => false],
        'fr-PM' => ['name' => 'français (Saint-Pierre-et-Miquelon)', 'rtl' => false],
        'fr-RE' => ['name' => 'français (La Réunion)', 'rtl' => false],
        'fr-RW' => ['name' => 'français (Rwanda)', 'rtl' => false],
        'fr-SC' => ['name' => 'français (Seychelles)', 'rtl' => false],
        'fr-SN' => ['name' => 'français (Sénégal)', 'rtl' => false],
        'fr-SY' => ['name' => 'français (Syrie)', 'rtl' => false],
        'fr-TD' => ['name' => 'français (Tchad)', 'rtl' => false],
        'fr-TG' => ['name' => 'français (Togo)', 'rtl' => false],
        'fr-TN' => ['name' => 'français (Tunisie)', 'rtl' => false],
        'fr-VU' => ['name' => 'français (Vanuatu)', 'rtl' => false],
        'fr-WF' => ['name' => 'français (Wallis-et-Futuna)', 'rtl' => false],
        'fr-YT' => ['name' => 'français (Mayotte)', 'rtl' => false],
        'fur-IT' => ['name' => 'furlan (Italie)', 'rtl' => false],
        'fy-NL' => ['name' => 'Frysk (Nederlân)', 'rtl' => false],
        'ga-IE' => ['name' => 'Gaeilge (Éire)', 'rtl' => false],
        'gd-GB' => ['name' => 'Gàidhlig (An Rìoghachd Aonaichte)', 'rtl' => false],
        'gl-ES' => ['name' => 'galego (España)', 'rtl' => false],
        'gsw-CH' => ['name' => 'Schwiizertüütsch (Schwiiz)', 'rtl' => false],
        'gsw-FR' => ['name' => 'Schwiizertüütsch (Frankriich)', 'rtl' => false],
        'gsw-LI' => ['name' => 'Schwiizertüütsch (Liächteschtäi)', 'rtl' => false],
        'gu-IN' => ['name' => 'ગુજરાતી (ભારત)', 'rtl' => false],
        'guz-KE' => ['name' => 'Ekegusii (Kenya)', 'rtl' => false],
        'gv-IM' => ['name' => 'Gaelg (Ellan Vannin)', 'rtl' => false],
        'ha-GH' => ['name' => 'Hausa (Gana)', 'rtl' => false],
        'ha-NE' => ['name' => 'Hausa (Nijar)', 'rtl' => false],
        'ha-NG' => ['name' => 'Hausa (Najeriya)', 'rtl' => false],
        'haw-US' => ['name' => 'ʻŌlelo Hawaiʻi (ʻAmelika Hui Pū ʻIa)', 'rtl' => false],
        'he-IL' => ['name' => 'עברית (ישראל)', 'rtl' => true],
        'hi-IN' => ['name' => 'हिन्दी (भारत)', 'rtl' => false],
        'hr-BA' => ['name' => 'hrvatski (Bosna i Hercegovina)', 'rtl' => false],
        'hr-HR' => ['name' => 'hrvatski (Hrvatska)', 'rtl' => false],
        'hsb-DE' => ['name' => 'hornjoserbšćina (Němska)', 'rtl' => false],
        'hu-HU' => ['name' => 'magyar (Magyarország)', 'rtl' => false],
        'hy-AM' => ['name' => 'հայերեն (Հայաստան)', 'rtl' => false],
        'id-ID' => ['name' => 'Indonesia (Indonesia)', 'rtl' => false],
        'ig-NG' => ['name' => 'Igbo (Naịjịrịa)', 'rtl' => false],
        'ii-CN' => ['name' => 'ꆈꌠꉙ (ꍏꇩ)', 'rtl' => false],
        'is-IS' => ['name' => 'íslenska (Ísland)', 'rtl' => false],
        'it-CH' => ['name' => 'italiano (Svizzera)', 'rtl' => false],
        'it-IT' => ['name' => 'italiano (Italia)', 'rtl' => false],
        'it-SM' => ['name' => 'italiano (San Marino)', 'rtl' => false],
        'it-VA' => ['name' => 'italiano (Città del Vaticano)', 'rtl' => false],
        'ja-JP' => ['name' => '日本語 (日本)', 'rtl' => false],
        'jgo-CM' => ['name' => 'Ndaꞌa (Kamɛlûn)', 'rtl' => false],
        'jmc-TZ' => ['name' => 'Kimachame (Tanzania)', 'rtl' => false],
        'ka-GE' => ['name' => 'ქართული (საქართველო)', 'rtl' => false],
        'kab-DZ' => ['name' => 'Taqbaylit (Lezzayer)', 'rtl' => false],
        'kam-KE' => ['name' => 'Kikamba (Kenya)', 'rtl' => false],
        'kde-TZ' => ['name' => 'Chimakonde (Tanzania)', 'rtl' => false],
        'kea-CV' => ['name' => 'kabuverdianu (Kabu Verdi)', 'rtl' => false],
        'khq-ML' => ['name' => 'Koyra ciini (Maali)', 'rtl' => false],
        'ki-KE' => ['name' => 'Gikuyu (Kenya)', 'rtl' => false],
        'kk-KZ' => ['name' => 'қазақ тілі (Қазақстан)', 'rtl' => false],
        'kkj-CM' => ['name' => 'kakɔ (Kamɛrun)', 'rtl' => false],
        'kl-GL' => ['name' => 'kalaallisut (Kalaallit Nunaat)', 'rtl' => false],
        'kln-KE' => ['name' => 'Kalenjin (Emetab Kenya)', 'rtl' => false],
        'km-KH' => ['name' => 'ខ្មែរ (កម្ពុជា)', 'rtl' => false],
        'kn-IN' => ['name' => 'ಕನ್ನಡ (ಭಾರತ)', 'rtl' => false],
        'ko-KP' => ['name' => '한국어(조선민주주의인민공화국)', 'rtl' => false],
        'ko-KR' => ['name' => '한국어(대한민국)', 'rtl' => false],
        'kok-IN' => ['name' => 'कोंकणी (भारत)', 'rtl' => false],
        'ks-IN' => ['name' => 'کٲشُر (ہِنٛدوستان)', 'rtl' => true],
        'ksb-TZ' => ['name' => 'Kishambaa (Tanzania)', 'rtl' => false],
        'ksf-CM' => ['name' => 'rikpa (kamɛrún)', 'rtl' => false],
        'ksh-DE' => ['name' => 'Kölsch en Doütschland', 'rtl' => false],
        'kw-GB' => ['name' => 'kernewek (Rywvaneth Unys)', 'rtl' => false],
        'ky-KG' => ['name' => 'кыргызча (Кыргызстан)', 'rtl' => false],
        'lag-TZ' => ['name' => 'Kɨlaangi (Taansanía)', 'rtl' => false],
        'lb-LU' => ['name' => 'Lëtzebuergesch (Lëtzebuerg)', 'rtl' => false],
        'lg-UG' => ['name' => 'Luganda (Yuganda)', 'rtl' => false],
        'lkt-US' => ['name' => 'Lakȟólʼiyapi (Mílahaŋska Tȟamákȟočhe)', 'rtl' => false],
        'ln-AO' => ['name' => 'lingála (Angóla)', 'rtl' => false],
        'ln-CD' => ['name' => 'lingála (Republíki ya Kongó Demokratíki)', 'rtl' => false],
        'ln-CF' => ['name' => 'lingála (Repibiki ya Afríka ya Káti)', 'rtl' => false],
        'ln-CG' => ['name' => 'lingála (Kongo)', 'rtl' => false],
        'lo-LA' => ['name' => 'ລາວ (ລາວ)', 'rtl' => false],
        'lrc-IQ' => ['name' => 'لۊری شومالی (IQ)', 'rtl' => true],
        'lrc-IR' => ['name' => 'لۊری شومالی (IR)', 'rtl' => true],
        'lt-LT' => ['name' => 'lietuvių (Lietuva)', 'rtl' => false],
        'lu-CD' => ['name' => 'Tshiluba (Ditunga wa Kongu)', 'rtl' => false],
        'luo-KE' => ['name' => 'Dholuo (Kenya)', 'rtl' => false],
        'luy-KE' => ['name' => 'Luluhia (Kenya)', 'rtl' => false],
        'lv-LV' => ['name' => 'latviešu (Latvija)', 'rtl' => false],
        'mas-KE' => ['name' => 'Maa (Kenya)', 'rtl' => false],
        'mas-TZ' => ['name' => 'Maa (Tansania)', 'rtl' => false],
        'mer-KE' => ['name' => 'Kĩmĩrũ (Kenya)', 'rtl' => false],
        'mfe-MU' => ['name' => 'kreol morisien (Moris)', 'rtl' => false],
        'mg-MG' => ['name' => 'Malagasy (Madagasikara)', 'rtl' => false],
        'mgh-MZ' => ['name' => 'Makua (Umozambiki)', 'rtl' => false],
        'mgo-CM' => ['name' => 'metaʼ (Kamalun)', 'rtl' => false],
        'mk-MK' => ['name' => 'македонски (Македонија)', 'rtl' => false],
        'ml-IN' => ['name' => 'മലയാളം (ഇന്ത്യ)', 'rtl' => false],
        'mn-MN' => ['name' => 'монгол (Монгол)', 'rtl' => false],
        'mr-IN' => ['name' => 'मराठी (भारत)', 'rtl' => false],
        'ms-BN' => ['name' => 'Melayu (Brunei)', 'rtl' => false],
        'ms-MY' => ['name' => 'Melayu (Malaysia)', 'rtl' => false],
        'ms-SG' => ['name' => 'Melayu (Singapura)', 'rtl' => false],
        'mt-MT' => ['name' => 'Malti (Malta)', 'rtl' => false],
        'mua-CM' => ['name' => 'MUNDAŊ (kameruŋ)', 'rtl' => false],
        'my-MM' => ['name' => 'မြန်မာ (မြန်မာ)', 'rtl' => false],
        'mzn-IR' => ['name' => 'مازرونی (ایران)', 'rtl' => true],
        'naq-NA' => ['name' => 'Khoekhoegowab (Namibiab)', 'rtl' => false],
        'nb-NO' => ['name' => 'norsk bokmål (Norge)', 'rtl' => false],
        'nb-SJ' => ['name' => 'norsk bokmål (Svalbard og Jan Mayen)', 'rtl' => false],
        'nd-ZW' => ['name' => 'isiNdebele (Zimbabwe)', 'rtl' => false],
        'nds-DE' => ['name' => 'Plattdüütsch (DE)', 'rtl' => false],
        'nds-NL' => ['name' => 'Plattdüütsch (NL)', 'rtl' => false],
        'ne-IN' => ['name' => 'नेपाली (भारत)', 'rtl' => false],
        'ne-NP' => ['name' => 'नेपाली (नेपाल)', 'rtl' => false],
        'nl-AW' => ['name' => 'Nederlands (Aruba)', 'rtl' => false],
        'nl-BE' => ['name' => 'Nederlands (België)', 'rtl' => false],
        'nl-BQ' => ['name' => 'Nederlands (Caribisch Nederland)', 'rtl' => false],
        'nl-CW' => ['name' => 'Nederlands (Curaçao)', 'rtl' => false],
        'nl-NL' => ['name' => 'Nederlands (Nederland)', 'rtl' => false],
        'nl-SR' => ['name' => 'Nederlands (Suriname)', 'rtl' => false],
        'nl-SX' => ['name' => 'Nederlands (Sint-Maarten)', 'rtl' => false],
        'nmg-CM' => ['name' => 'Kwasio (Kamerun)', 'rtl' => false],
        'nn-NO' => ['name' => 'nynorsk (Noreg)', 'rtl' => false],
        'nnh-CM' => ['name' => 'Shwóŋò ngiembɔɔn (Kàmalûm)', 'rtl' => false],
        'nus-SS' => ['name' => 'Thok Nath (SS)', 'rtl' => false],
        'nyn-UG' => ['name' => 'Runyankore (Uganda)', 'rtl' => false],
        'om-ET' => ['name' => 'Oromoo (Itoophiyaa)', 'rtl' => false],
        'om-KE' => ['name' => 'Oromoo (Keeniyaa)', 'rtl' => false],
        'or-IN' => ['name' => 'ଓଡ଼ିଆ (ଭାରତ)', 'rtl' => false],
        'os-GE' => ['name' => 'ирон (Гуырдзыстон)', 'rtl' => false],
        'os-RU' => ['name' => 'ирон (Уӕрӕсе)', 'rtl' => false],
        'pa-Arab-PK' => ['name' => 'پنجابی (پاکستان)', 'rtl' => true],
        'pa-Guru-IN' => ['name' => 'ਪੰਜਾਬੀ (ਭਾਰਤ)', 'rtl' => false],
        'pl-PL' => ['name' => 'polski (Polska)', 'rtl' => false],
        'ps-AF' => ['name' => 'پښتو (افغانستان)', 'rtl' => true],
        'pt-AO' => ['name' => 'português (Angola)', 'rtl' => false],
        'pt-BR' => ['name' => 'português (Brasil)', 'rtl' => false],
        'pt-CH' => ['name' => 'português (Suíça)', 'rtl' => false],
        'pt-CV' => ['name' => 'português (Cabo Verde)', 'rtl' => false],
        'pt-GQ' => ['name' => 'português (Guiné Equatorial)', 'rtl' => false],
        'pt-GW' => ['name' => 'português (Guiné-Bissau)', 'rtl' => false],
        'pt-LU' => ['name' => 'português (Luxemburgo)', 'rtl' => false],
        'pt-MO' => ['name' => 'português (Macau, RAE da China)', 'rtl' => false],
        'pt-MZ' => ['name' => 'português (Moçambique)', 'rtl' => false],
        'pt-PT' => ['name' => 'português (Portugal)', 'rtl' => false],
        'pt-ST' => ['name' => 'português (São Tomé e Príncipe)', 'rtl' => false],
        'pt-TL' => ['name' => 'português (Timor-Leste)', 'rtl' => false],
        'qu-BO' => ['name' => 'Runasimi (Bolivia)', 'rtl' => false],
        'qu-EC' => ['name' => 'Runasimi (Ecuador)', 'rtl' => false],
        'qu-PE' => ['name' => 'Runasimi (Perú)', 'rtl' => false],
        'rm-CH' => ['name' => 'rumantsch (Svizra)', 'rtl' => false],
        'rn-BI' => ['name' => 'Ikirundi (Uburundi)', 'rtl' => false],
        'ro-MD' => ['name' => 'română (Republica Moldova)', 'rtl' => false],
        'ro-RO' => ['name' => 'română (România)', 'rtl' => false],
        'rof-TZ' => ['name' => 'Kihorombo (Tanzania)', 'rtl' => false],
        'ru-BY' => ['name' => 'русский (Беларусь)', 'rtl' => false],
        'ru-KG' => ['name' => 'русский (Киргизия)', 'rtl' => false],
        'ru-KZ' => ['name' => 'русский (Казахстан)', 'rtl' => false],
        'ru-MD' => ['name' => 'русский (Молдова)', 'rtl' => false],
        'ru-RU' => ['name' => 'русский (Россия)', 'rtl' => false],
        'ru-UA' => ['name' => 'русский (Украина)', 'rtl' => false],
        'rw-RW' => ['name' => 'Kinyarwanda (U Rwanda)', 'rtl' => false],
        'rwk-TZ' => ['name' => 'Kiruwa (Tanzania)', 'rtl' => false],
        'sah-RU' => ['name' => 'саха тыла (Арассыыйа)', 'rtl' => false],
        'saq-KE' => ['name' => 'Kisampur (Kenya)', 'rtl' => false],
        'sbp-TZ' => ['name' => 'Ishisangu (Tansaniya)', 'rtl' => false],
        'se-FI' => ['name' => 'davvisámegiella (Suopma)', 'rtl' => false],
        'se-NO' => ['name' => 'davvisámegiella (Norga)', 'rtl' => false],
        'se-SE' => ['name' => 'davvisámegiella (Ruoŧŧa)', 'rtl' => false],
        'seh-MZ' => ['name' => 'sena (Moçambique)', 'rtl' => false],
        'ses-ML' => ['name' => 'Koyraboro senni (Maali)', 'rtl' => false],
        'sg-CF' => ['name' => 'Sängö (Ködörösêse tî Bêafrîka)', 'rtl' => false],
        'shi-Latn-MA' => ['Tashelḥiyt (lmɣrib)', 'rtl' => false],
        'shi-Tfng-MA' => ['name' => 'ⵜⴰⵛⵍⵃⵉⵜ (ⵍⵎⵖⵔⵉⴱ)', 'rtl' => false],
        'si-LK' => ['name' => 'සිංහල (ශ්‍රී ලංකාව)', 'rtl' => false],
        'sk-SK' => ['name' => 'slovenčina (Slovensko)', 'rtl' => false],
        'sl-SI' => ['name' => 'slovenščina (Slovenija)', 'rtl' => false],
        'smn-FI' => ['name' => 'anarâškielâ (Suomâ)', 'rtl' => false],
        'sn-ZW' => ['name' => 'chiShona (Zimbabwe)', 'rtl' => false],
        'so-DJ' => ['name' => 'Soomaali (Jabuuti)', 'rtl' => false],
        'so-ET' => ['name' => 'Soomaali (Itoobiya)', 'rtl' => false],
        'so-KE' => ['name' => 'Soomaali (Kiiniya)', 'rtl' => false],
        'so-SO' => ['name' => 'Soomaali (Soomaaliya)', 'rtl' => false],
        'sq-AL' => ['name' => 'shqip (Shqipëri)', 'rtl' => false],
        'sq-MK' => ['name' => 'shqip (Maqedoni)', 'rtl' => false],
        'sq-XK' => ['name' => 'shqip (Kosovë)', 'rtl' => false],
        'sr-Cyrl-BA' => ['name' => 'српски (Босна и Херцеговина)', 'rtl' => false],
        'sr-Cyrl-ME' => ['name' => 'српски (Црна Гора)', 'rtl' => false],
        'sr-Cyrl-RS' => ['name' => 'српски (Србија)', 'rtl' => false],
        'sr-Cyrl-XK' => ['name' => 'српски (Косово)', 'rtl' => false],
        'sr-Latn-BA' => ['name' => 'srpski (Bosna i Hercegovina)', 'rtl' => false],
        'sr-Latn-ME' => ['name' => 'srpski (Crna Gora)', 'rtl' => false],
        'sr-Latn-RS' => ['name' => 'srpski (Srbija)', 'rtl' => false],
        'sr-Latn-XK' => ['name' => 'srpski (Kosovo)', 'rtl' => false],
        'sv-AX' => ['name' => 'svenska (Åland)', 'rtl' => false],
        'sv-FI' => ['name' => 'svenska (Finland)', 'rtl' => false],
        'sv-SE' => ['name' => 'svenska (Sverige)', 'rtl' => false],
        'sw-CD' => ['name' => 'Kiswahili (Jamhuri ya Kidemokrasia ya Kongo)', 'rtl' => false],
        'sw-KE' => ['name' => 'Kiswahili (Kenya)', 'rtl' => false],
        'sw-TZ' => ['name' => 'Kiswahili (Tanzania)', 'rtl' => false],
        'sw-UG' => ['name' => 'Kiswahili (Uganda)', 'rtl' => false],
        'ta-IN' => ['name' => 'தமிழ் (இந்தியா)', 'rtl' => false],
        'ta-LK' => ['name' => 'தமிழ் (இலங்கை)', 'rtl' => false],
        'ta-MY' => ['name' => 'தமிழ் (மலேசியா)', 'rtl' => false],
        'ta-SG' => ['name' => 'தமிழ் (சிங்கப்பூர்)', 'rtl' => false],
        'te-IN' => ['name' => 'తెలుగు (భారతదేశం)', 'rtl' => false],
        'teo-KE' => ['name' => 'Kiteso (Kenia)', 'rtl' => false],
        'teo-UG' => ['name' => 'Kiteso (Uganda)', 'rtl' => false],
        'tg-TJ' => ['name' => 'тоҷикӣ (Тоҷикистон)', 'rtl' => false],
        'th-TH' => ['name' => 'ไทย (ไทย)', 'rtl' => false],
        'ti-ER' => ['name' => 'ትግርኛ (ኤርትራ)', 'rtl' => false],
        'ti-ET' => ['name' => 'ትግርኛ (ኢትዮጵያ)', 'rtl' => false],
        'to-TO' => ['name' => 'lea fakatonga (Tonga)', 'rtl' => false],
        'tr-CY' => ['name' => 'Türkçe (Kıbrıs)', 'rtl' => false],
        'tr-TR' => ['name' => 'Türkçe (Türkiye)', 'rtl' => false],
        'tt-RU' => ['name' => 'татар (Россия)', 'rtl' => false],
        'twq-NE' => ['name' => 'Tasawaq senni (Nižer)', 'rtl' => false],
        'tzm-MA' => ['name' => 'Tamaziɣt n laṭlaṣ (Meṛṛuk)', 'rtl' => false],
        'ug-CN' => ['name' => 'ئۇيغۇرچە (جۇڭگو)', 'rtl' => true],
        'uk-RU' => ['name' => 'українська (Росія)', 'rtl' => false],
        'uk-UA' => ['name' => 'українська (Україна)', 'rtl' => false],
        'ur-IN' => ['name' => 'اردو (بھارت)', 'rtl' => true],
        'ur-PK' => ['name' => 'اردو (پاکستان)', 'rtl' => true],
        'uz-Arab-AF' => ['name' => 'اوزبیک (افغانستان)', 'rtl' => false],
        'uz-Cyrl-UZ' => ['name' => 'ўзбекча (Ўзбекистон)', 'rtl' => false],
        'uz-Latn-UZ' => ['name' => 'o‘zbek (Oʻzbekiston)', 'rtl' => false],
        'vai-Latn-LR' => ['name' => 'Vai (Laibhiya)', 'rtl' => false],
        'vai-Vaii-LR' => ['name' => 'ꕙꔤ (ꕞꔤꔫꕩ)', 'rtl' => false],
        'vi-VN' => ['name' => 'Tiếng Việt (Việt Nam)', 'rtl' => false],
        'vun-TZ' => ['name' => 'Kyivunjo (Tanzania)', 'rtl' => false],
        'wae-CH' => ['name' => 'Walser (Schwiz)', 'rtl' => false],
        'wo-SN' => ['name' => 'Wolof (Senegaal)', 'rtl' => false],
        'xog-UG' => ['name' => 'Olusoga (Yuganda)', 'rtl' => false],
        'yav-CM' => ['name' => 'nuasue (Kemelún)', 'rtl' => false],
        'yi' => ['name' => 'ייִדיש', 'rtl' => true],
        'yo-BJ' => ['name' => 'Èdè Yorùbá (Orílɛ́ède Bɛ̀nɛ̀)', 'rtl' => false],
        'yo-NG' => ['name' => 'Èdè Yorùbá (Orílẹ́ède Nàìjíríà)', 'rtl' => false],
        'yue-Hans-CN' => ['name' => '粤语 (简体，中华人民共和国)', 'rtl' => false],
        'yue-Hant-HK' => ['name' => '粵語 (繁體，中華人民共和國香港特別行政區)', 'rtl' => false],
        'zgh-MA' => ['name' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⵎⵖⵔⵉⴱ)', 'rtl' => false],
        'zh-Hans-CN' => ['name' => '中文（简体，中国)', 'rtl' => false],
        'zh-Hans-HK' => ['name' => '中文（简体，中国香港特别行政区', 'rtl' => false],
        'zh-Hans-MO' => ['name' => '中文（简体，中国澳门特别行政区)', 'rtl' => false],
        'zh-Hans-SG' => ['name' => '中文（简体，新加坡)', 'rtl' => false],
        'zh-Hant-HK' => ['name' => '中文（繁體字，中國香港特別行政區)', 'rtl' => false],
        'zh-Hant-MO' => ['name' => '中文（繁體字，中國澳門特別行政區)', 'rtl' => false],
        'zh-Hant-TW' => ['name' => '中文（繁體，台灣)', 'rtl' => false],
        'zu-ZA' => ['name' => 'isiZulu (iNingizimu Afrika)', 'rtl' => false]
    ];
    public $CurrencyList = [
        'AED' => ['symbol' => '.د.إ • Dh', 'code' => '784'],
        'AFN' => ['symbol' => '؋ • Af', 'code' => '971'],
        'ALL' => ['symbol' => 'L', 'code' => '008'],
        'AMD' => ['symbol' => '֏', 'code' => '051'],
        'ANG' => ['symbol' => 'ƒ', 'code' => '532'],
        'AOA' => ['symbol' => 'Kz', 'code' => '973'],
        'ARS' => ['symbol' => '$', 'code' => '032'],
        'AUD' => ['symbol' => '$', 'code' => '036'],
        'AWG' => ['symbol' => 'ƒ', 'code' => '533'],
        'AZN' => ['symbol' => '₼', 'code' => '944'],
        'BAM' => ['symbol' => 'KM', 'code' => '977'],
        'BBD' => ['symbol' => '$', 'code' => '052'],
        'BDT' => ['symbol' => '৳', 'code' => '050'],
        'BGN' => ['symbol' => 'лв', 'code' => '975'],
        'BHD' => ['symbol' => '.د.ب • BD', 'code' => '048'],
        'BIF' => ['symbol' => '₣', 'code' => '108'],
        'BMD' => ['symbol' => '$', 'code' => '060'],
        'BND' => ['symbol' => '$', 'code' => '096'],
        'BOB' => ['symbol' => '$', 'code' => '068'],
        'BRL' => ['symbol' => '$', 'code' => '986'],
        'BSD' => ['symbol' => '$', 'code' => '044'],
        'BTN' => ['symbol' => 'Nu', 'code' => '064'],
        'BWP' => ['symbol' => 'P', 'code' => '072'],
        'BYN' => ['symbol' => 'Br', 'code' => '933'],
        'BZD' => ['symbol' => '$', 'code' => '084'],
        'CAD' => ['symbol' => '$', 'code' => '124'],
        'CDF' => ['symbol' => '₣', 'code' => '976'],
        'CHF' => ['symbol' => '₣', 'code' => '756'],
        'CLP' => ['symbol' => '$', 'code' => '152'],
        'CNY' => ['symbol' => '¥', 'code' => '156'],
        'COP' => ['symbol' => '$', 'code' => '170'],
        'CRC' => ['symbol' => '₡', 'code' => '188'],
        'CUP' => ['symbol' => '$', 'code' => '192'],
        'CVE' => ['symbol' => '$', 'code' => '132'],
        'CZK' => ['symbol' => 'Kč', 'code' => '203'],
        'DJF' => ['symbol' => '₣', 'code' => '262'],
        'DKK' => ['symbol' => 'kr', 'code' => '208'],
        'DOP' => ['symbol' => '$', 'code' => '214'],
        'DZD' => ['symbol' => '.د.ج • DA', 'code' => '012'],
        'EGP' => ['symbol' => '.ج.م • LE', 'code' => '818'],
        'ERN' => ['symbol' => 'Nfk', 'code' => '232'],
        'ETB' => ['symbol' => 'Br', 'code' => '230'],
        'EUR' => ['symbol' => '€', 'code' => '978'],
        'FJD' => ['symbol' => '$', 'code' => '242'],
        'GBP' => ['symbol' => '£', 'code' => '826'],
        'GEL' => ['symbol' => '₾', 'code' => '981'],
        'GHS' => ['symbol' => '₵', 'code' => '936'],
        'GIP' => ['symbol' => '£', 'code' => '292'],
        'GMD' => ['symbol' => 'D', 'code' => '270'],
        'GNF' => ['symbol' => '₣', 'code' => '324'],
        'GTQ' => ['symbol' => 'Q', 'code' => '320'],
        'GYD' => ['symbol' => '$', 'code' => '328'],
        'HKD' => ['symbol' => '$', 'code' => '344'],
        'HNL' => ['symbol' => 'L', 'code' => '340'],
        'HRK' => ['symbol' => 'Kn', 'code' => '191'],
        'HTG' => ['symbol' => 'G', 'code' => '332'],
        'HUF' => ['symbol' => 'Ft', 'code' => '348'],
        'IDR' => ['symbol' => 'Rp', 'code' => '360'],
        'ILS' => ['symbol' => '₪', 'code' => '376'],
        'INR' => ['symbol' => '₹', 'code' => '356'],
        'IQD' => ['symbol' => '.د.ع • ID', 'code' => '368'],
        'IRR' => ['symbol' => '﷼ • IR', 'code' => '364'],
        'ISK' => ['symbol' => 'kr', 'code' => '352'],
        'JMD' => ['symbol' => '$', 'code' => '388'],
        'JOD' => ['symbol' => '.د.إ • JD', 'code' => '400'],
        'JPY' => ['symbol' => '¥', 'code' => '392'],
        'KES' => ['symbol' => 'KSh', 'code' => '404'],
        'KGS' => ['symbol' => 'с', 'code' => '417'],
        'KHR' => ['symbol' => '៛', 'code' => '116'],
        'KMF' => ['symbol' => '₣', 'code' => '174'],
        'KPW' => ['symbol' => '원', 'code' => '408'],
        'KRW' => ['symbol' => '₩', 'code' => '410'],
        'KWD' => ['symbol' => '.د.ك • KD', 'code' => '414'],
        'KYD' => ['symbol' => '$', 'code' => '136'],
        'KZT' => ['symbol' => '₸', 'code' => '398'],
        'LAK' => ['symbol' => '₭', 'code' => '418'],
        'LBP' => ['symbol' => '.ل.ل', 'code' => '422'],
        'LKR' => ['symbol' => 'Re', 'code' => '144'],
        'LRD' => ['symbol' => '$', 'code' => '430'],
        'LSL' => ['symbol' => 'L', 'code' => '426'],
        'LYD' => ['symbol' => '.د.ل • LD', 'code' => '434'],
        'MAD' => ['symbol' => '.د.م • Dh', 'code' => '504'],
        'MDL' => ['symbol' => 'L', 'code' => '498'],
        'MGA' => ['symbol' => 'Ar.', 'code' => '969'],
        'MKD' => ['symbol' => 'ден.', 'code' => '807'],
        'MMK' => ['symbol' => 'K', 'code' => '104'],
        'MNT' => ['symbol' => '₮', 'code' => '496'],
        'MOP' => ['symbol' => '$', 'code' => '446'],
        'MRU' => ['symbol' => 'UM', 'code' => '929'],
        'MUR' => ['symbol' => 'Re', 'code' => '480'],
        'MVR' => ['symbol' => '.ރ • Rf', 'code' => '462'],
        'MWK' => ['symbol' => 'K', 'code' => '454'],
        'MXN' => ['symbol' => '$', 'code' => '484'],
        'MYR' => ['symbol' => 'RM', 'code' => '458'],
        'MZN' => ['symbol' => 'MT', 'code' => '943'],
        'NAD' => ['symbol' => 'N$', 'code' => '516'],
        'NGN' => ['symbol' => '₦', 'code' => '566'],
        'NIO' => ['symbol' => '$', 'code' => '558'],
        'NOK' => ['symbol' => 'kr', 'code' => '578'],
        'NPR' => ['symbol' => 'Re', 'code' => '524'],
        'NZD' => ['symbol' => '$', 'code' => '554'],
        'OMR' => ['symbol' => '﷼ • RO', 'code' => '512'],
        'PAB' => ['symbol' => 'B/.', 'code' => '590'],
        'PEN' => ['symbol' => 'S/', 'code' => '604'],
        'PGK' => ['symbol' => 'K', 'code' => '598'],
        'PHP' => ['symbol' => '₱', 'code' => '608'],
        'PKR' => ['symbol' => 'Re', 'code' => '586'],
        'PLN' => ['symbol' => 'zł', 'code' => '985'],
        'PYG' => ['symbol' => '₲', 'code' => '600'],
        'QAR' => ['symbol' => '﷼ • QR', 'code' => '634'],
        'RON' => ['symbol' => 'L', 'code' => '946'],
        'RSD' => ['symbol' => 'din. • дин.	', 'code' => '941'],
        'RUB' => ['symbol' => '₽', 'code' => '643'],
        'RWF' => ['symbol' => '₣', 'code' => '646'],
        'SAR' => ['symbol' => '﷼ • SR', 'code' => '682'],
        'SBD' => ['symbol' => '$', 'code' => '090'],
        'SCR' => ['symbol' => 'Re', 'code' => '690'],
        'SDG' => ['symbol' => '£', 'code' => '938'],
        'SEK' => ['symbol' => 'kr', 'code' => '752'],
        'SGD' => ['symbol' => '$', 'code' => '702'],
        'SLL' => ['symbol' => 'Le', 'code' => '694'],
        'SOS' => ['symbol' => 'S', 'code' => '706'],
        'SRD' => ['symbol' => '$', 'code' => '968'],
        'SSP' => ['symbol' => 'SSP', 'code' => '728'],
        'STN' => ['symbol' => 'Db', 'code' => '930'],
        'SVC' => ['symbol' => '₡', 'code' => '222'],
        'SYP' => ['symbol' => '.ل.س • S£', 'code' => '760'],
        'SZL' => ['symbol' => 'L', 'code' => '748'],
        'THB' => ['symbol' => '฿', 'code' => '764'],
        'TJS' => ['symbol' => 'с.', 'code' => '972'],
        'TMT' => ['symbol' => 'm', 'code' => '934'],
        'TND' => ['symbol' => '.د.ت • TD', 'code' => '788'],
        'TOP' => ['symbol' => '$', 'code' => '776'],
        'TRY' => ['symbol' => '₺', 'code' => '949'],
        'TTD' => ['symbol' => '$', 'code' => '780'],
        'TWD' => ['symbol' => 'NT$', 'code' => '901'],
        'TZS' => ['symbol' => 'TSh', 'code' => '834'],
        'UAH' => ['symbol' => '₴', 'code' => '980'],
        'UGX' => ['symbol' => 'USh', 'code' => '800'],
        'USD' => ['symbol' => '$', 'code' => '840'],
        'UYU' => ['symbol' => '$', 'code' => '858'],
        'UZS' => ['symbol' => 'so’m • сўм', 'code' => '860'],
        'VES' => ['symbol' => 'Bs. S.', 'code' => '928'],
        'VND' => ['symbol' => '₫', 'code' => '704'],
        'VUV' => ['symbol' => 'Vt', 'code' => '548'],
        'WST' => ['symbol' => '$', 'code' => '882'],
        'XAF' => ['symbol' => '₣', 'code' => '950'],
        'XCD' => ['symbol' => '$', 'code' => '951'],
        'XOF' => ['symbol' => '₣', 'code' => '952'],
        'XPF' => ['symbol' => '₣', 'code' => '953'],
        'YER' => ['symbol' => '﷼ • YR', 'code' => '886'],
        'ZAR' => ['symbol' => 'R', 'code' => '710'],
        'ZMW' => ['symbol' => 'K', 'code' => '967'],
        'ZWL' => ['symbol' => 'Z$', 'code' => '932'],
        'BTC' => ['symbol' => '₿', 'code' => '000']
    ];
    public function __construct()
    {
        $this->TimeZone = timezone_identifiers_list();
        $DateTime = new \DateTimeImmutable('2024-09-01 01:05:05');
        foreach ($this->DataFormat as $key => $Value) {
            $this->DataFormat[$key]['example'] = $DateTime->format($Value['format']);
        }
        foreach ($this->TimeFormat as $key => $Value) {
            $this->TimeFormat[$key]['example'] = $DateTime->format($Value['format']);
        }

    }
    public function detThemes(string $Language): array
    {
        $translator = new Translator($Language);
        foreach ($this->Themes as $key => $Value) {
            $this->Themes[$key]['text'] = $translator->trans($Value['key'], [], 'arrayaccess', locale: $Language);
        }
        return $this->Themes;
    }
    public function detEffects(string $Language): array
    {
        $translator = new Translator($Language);
        foreach ($this->Effects as $key => $Value) {
            $this->Effects[$key]['text'] = $translator->trans($Value['key'], [], 'arrayaccess', locale: $Language);
        }
        return $this->Effects;
    }
    public function detLanguages(string $Language): array
    {
        $translator = new Translator($Language);
        foreach ($this->LanguageList as $key => $Value) {
            $this->LanguageList[$key]['translation'] = $translator->trans('languages.' . $key, [], 'arrayaccess', locale: $Language);
        }
        return $this->LanguageList;
    }
    public function detCurrency(string $Language): array
    {
        $translator = new Translator($Language);
        foreach ($this->CurrencyList as $key => $Value) {
            $this->CurrencyList[$key]['translation'] = $translator->trans('Currency.' . $key, [], 'arrayaccess', locale: $Language);
        }
        return $this->CurrencyList;
    }
}