framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            assets/: ""
            vendor/fortawesome/font-awesome/: "font-awesome"
            vendor/twbs/bootstrap/: "bootstrap"
            vendor/twbs/bootstrap-icons/: "bootstrap-icons"
